travis:
  secure:
    BINSTAR_TOKEN: FlAajh6BgekIWNr9NgTjr1lfWPumE6hev3TBvcYTiUxHuggl8AcmbxFoDmw8GRt/tqJMueSjZG0zUJu9ESLVV/tViKQ58zykQwNWySOVOk2Ik9Ucc4DPaqGKDGJT8goLF7UZ+XxNqn3fyKNSQ27LbUok1iVWc6DNq+eCDtYQFetosc8PwzD0vV9AxErGQAwsqfQQXuw/Ls5GFlQot325UnWyicm28oKabdW2gzbLR4UR5Auop73W/zDWoYIoO98Vbee/BgsRyEg7WpG8v9aizktV1WCISYkQuN34OLqP4cuUeHmoyMgpCfNU7XAkOmFWjJfm/TLOoOOytV4jhQCW5xZKN1w/oVL4DmbY70E/ixuNUYVPFKo6HHu4IjE/tkWzu8ZM5U9+4HzMMuO3l7s5AwN5OEPYZAn+3XwfiyE8dNctdTdkf/8F2nFDJHfQMLuHkezsWP2WyWZb9AX9/SF9rpIFOTsVqSbpkyepZe2sGM5rn9492k92vQQkijjN/XSNaLFssUicB7ZrOoW4zs3MbTKNI23aRr1lE+BXwyCG0ko5Xl7zVhbMQl++SDbr02YSlabvXP6+XegwBgdYaG3/b4emdIBUC5bzUbvXbNOd6U0fV5UGoocHXXverG24+oBbOKjhgFbZd9q4br7DaogIUnh1gay0pVeGrWh+fNUM9MQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
